from pathlib import Path
p=Path('/home/ubuntu/brasfoot_engine/scripts/career_gateway.py')
s=p.read_text()
needle='from engine.core.p1_commission_contract import audit_p1_commissions, protect_p1_commission_mutation, read_p1_commissions, read_p1_commission_state, persist_p1_commission, validate_p1_commission\n'
s=s.replace(needle, needle+'from engine.core.p1_category_domain10_contract import audit_p1_category_domain10s, protect_p1_category_domain10_mutation, read_p1_category_domain10s, read_p1_category_domain10_state, persist_p1_category_domain10, validate_p1_category_domain10\n',1)
needle='def p1_commission_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n'
fn="""def p1_category_domain10_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n    if action == 'p1_category_domain10_contracts': return {'items': read_p1_category_domain10s(connection), 'read_only': True}\n    if action == 'p1_category_domain10_state': return {'items': read_p1_category_domain10_state(connection, payload.get('category_domain10_key')), 'read_only': True}\n    if action == 'p1_category_domain10_validate': return validate_p1_category_domain10(connection, int(payload.get('item_id')))\n    if action == 'p1_category_domain10_persist': return persist_p1_category_domain10(connection, str(payload.get('category_domain10_key', '')), int(payload.get('category_domain10_id', 0)), str(payload.get('category_domain10_name', '')), dict(payload.get('category_domain10_payload') or {}), payload.get('club_id'), str(payload.get('status', 'ACTIVE')), str(payload.get('actor', '')))\n    if action == 'p1_category_domain10_protect': return protect_p1_category_domain10_mutation(connection, int(payload.get('item_id')), str(payload.get('actor', '')), dict(payload.get('mutation') or {}))\n    if action == 'p1_category_domain10_audit': return audit_p1_category_domain10s(connection)\n    raise ValueError('P1_CATEGORY_DOMAIN10_ACTION_INVALID')\n\n"""
s=s.replace(needle,fn+needle,1)
marker='        if action in {"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit"}:\n            return {"ok": True, **p1_commission_market(service.connection, action, payload)}\n'
s=s.replace(marker,marker+'        if action in {"p1_category_domain10_contracts", "p1_category_domain10_state", "p1_category_domain10_validate", "p1_category_domain10_persist", "p1_category_domain10_protect", "p1_category_domain10_audit"}:\n            return {"ok": True, **p1_category_domain10_market(service.connection, action, payload)}\n',1)
choices='"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit", '
s=s.replace(choices,choices+'"p1_category_domain10_contracts", "p1_category_domain10_state", "p1_category_domain10_validate", "p1_category_domain10_persist", "p1_category_domain10_protect", "p1_category_domain10_audit", ',1)
p.write_text(s)
