from pathlib import Path
p=Path('/home/ubuntu/brasfoot_engine/scripts/career_gateway.py')
s=p.read_text()
needle='from engine.core.p1_commission_contract import audit_p1_commissions, protect_p1_commission_mutation, read_p1_commissions, read_p1_commission_state, persist_p1_commission, validate_p1_commission\n'
s=s.replace(needle, needle+'from engine.core.p1_fisioterapia_contract import audit_p1_fisioterapias, protect_p1_fisioterapia_mutation, read_p1_fisioterapias, read_p1_fisioterapia_state, persist_p1_fisioterapia, validate_p1_fisioterapia\n',1)
needle='def p1_commission_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n'
fn="""def p1_fisioterapia_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n    if action == 'p1_fisioterapia_contracts': return {'items': read_p1_fisioterapias(connection), 'read_only': True}\n    if action == 'p1_fisioterapia_state': return {'items': read_p1_fisioterapia_state(connection, payload.get('fisioterapia_key')), 'read_only': True}\n    if action == 'p1_fisioterapia_validate': return validate_p1_fisioterapia(connection, int(payload.get('item_id')))\n    if action == 'p1_fisioterapia_persist': return persist_p1_fisioterapia(connection, str(payload.get('fisioterapia_key', '')), int(payload.get('fisioterapia_id', 0)), str(payload.get('fisioterapia_name', '')), dict(payload.get('fisioterapia_payload') or {}), payload.get('club_id'), str(payload.get('status', 'ACTIVE')), str(payload.get('actor', '')))\n    if action == 'p1_fisioterapia_protect': return protect_p1_fisioterapia_mutation(connection, int(payload.get('item_id')), str(payload.get('actor', '')), dict(payload.get('mutation') or {}))\n    if action == 'p1_fisioterapia_audit': return audit_p1_fisioterapias(connection)\n    raise ValueError('P1_FISIOTERAPIA_ACTION_INVALID')\n\n"""
s=s.replace(needle,fn+needle,1)
marker='        if action in {"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit"}:\n            return {"ok": True, **p1_commission_market(service.connection, action, payload)}\n'
s=s.replace(marker,marker+'        if action in {"p1_fisioterapia_contracts", "p1_fisioterapia_state", "p1_fisioterapia_validate", "p1_fisioterapia_persist", "p1_fisioterapia_protect", "p1_fisioterapia_audit"}:\n            return {"ok": True, **p1_fisioterapia_market(service.connection, action, payload)}\n',1)
choices='"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit", '
s=s.replace(choices,choices+'"p1_fisioterapia_contracts", "p1_fisioterapia_state", "p1_fisioterapia_validate", "p1_fisioterapia_persist", "p1_fisioterapia_protect", "p1_fisioterapia_audit", ',1)
p.write_text(s)
