from pathlib import Path
p=Path('/home/ubuntu/brasfoot_engine/scripts/career_gateway.py')
s=p.read_text()
needle='from engine.core.p1_commission_salario import audit_p1_commissions, protect_p1_commission_mutation, read_p1_commissions, read_p1_commission_state, persist_p1_commission, validate_p1_commission\n'
s=s.replace(needle, needle+'from engine.core.p1_salario_salario import audit_p1_salarios, protect_p1_salario_mutation, read_p1_salarios, read_p1_salario_state, persist_p1_salario, validate_p1_salario\n',1)
needle='def p1_commission_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n'
fn="""def p1_salario_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n    if action == 'p1_salario_salarios': return {'items': read_p1_salarios(connection), 'read_only': True}\n    if action == 'p1_salario_state': return {'items': read_p1_salario_state(connection, payload.get('salario_key')), 'read_only': True}\n    if action == 'p1_salario_validate': return validate_p1_salario(connection, int(payload.get('item_id')))\n    if action == 'p1_salario_persist': return persist_p1_salario(connection, str(payload.get('salario_key', '')), int(payload.get('salario_id', 0)), str(payload.get('salario_name', '')), dict(payload.get('salario_payload') or {}), payload.get('club_id'), str(payload.get('status', 'ACTIVE')), str(payload.get('actor', '')))\n    if action == 'p1_salario_protect': return protect_p1_salario_mutation(connection, int(payload.get('item_id')), str(payload.get('actor', '')), dict(payload.get('mutation') or {}))\n    if action == 'p1_salario_audit': return audit_p1_salarios(connection)\n    raise ValueError('P1_SALARIO_ACTION_INVALID')\n\n"""
s=s.replace(needle,fn+needle,1)
marker='        if action in {"p1_commission_salarios", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit"}:\n            return {"ok": True, **p1_commission_market(service.connection, action, payload)}\n'
s=s.replace(marker,marker+'        if action in {"p1_salario_salarios", "p1_salario_state", "p1_salario_validate", "p1_salario_persist", "p1_salario_protect", "p1_salario_audit"}:\n            return {"ok": True, **p1_salario_market(service.connection, action, payload)}\n',1)
choices='"p1_commission_salarios", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit", '
s=s.replace(choices,choices+'"p1_salario_salarios", "p1_salario_state", "p1_salario_validate", "p1_salario_persist", "p1_salario_protect", "p1_salario_audit", ',1)
p.write_text(s)
