from pathlib import Path
p=Path('/home/ubuntu/brasfoot_engine/scripts/career_gateway.py')
s=p.read_text()
needle='from engine.core.p1_commission_contract import audit_p1_commissions, protect_p1_commission_mutation, read_p1_commissions, read_p1_commission_state, persist_p1_commission, validate_p1_commission\n'
s=s.replace(needle, needle+'from engine.core.p1_captacao_contract import audit_p1_captacaos, protect_p1_captacao_mutation, read_p1_captacaos, read_p1_captacao_state, persist_p1_captacao, validate_p1_captacao\n',1)
needle='def p1_commission_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n'
fn="""def p1_captacao_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n    if action == 'p1_captacao_contracts': return {'items': read_p1_captacaos(connection), 'read_only': True}\n    if action == 'p1_captacao_state': return {'items': read_p1_captacao_state(connection, payload.get('captacao_key')), 'read_only': True}\n    if action == 'p1_captacao_validate': return validate_p1_captacao(connection, int(payload.get('item_id')))\n    if action == 'p1_captacao_persist': return persist_p1_captacao(connection, str(payload.get('captacao_key', '')), int(payload.get('captacao_id', 0)), str(payload.get('captacao_name', '')), dict(payload.get('captacao_payload') or {}), payload.get('club_id'), str(payload.get('status', 'ACTIVE')), str(payload.get('actor', '')))\n    if action == 'p1_captacao_protect': return protect_p1_captacao_mutation(connection, int(payload.get('item_id')), str(payload.get('actor', '')), dict(payload.get('mutation') or {}))\n    if action == 'p1_captacao_audit': return audit_p1_captacaos(connection)\n    raise ValueError('P1_CAPTACAO_ACTION_INVALID')\n\n"""
s=s.replace(needle,fn+needle,1)
marker='        if action in {"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit"}:\n            return {"ok": True, **p1_commission_market(service.connection, action, payload)}\n'
s=s.replace(marker,marker+'        if action in {"p1_captacao_contracts", "p1_captacao_state", "p1_captacao_validate", "p1_captacao_persist", "p1_captacao_protect", "p1_captacao_audit"}:\n            return {"ok": True, **p1_captacao_market(service.connection, action, payload)}\n',1)
choices='"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit", '
s=s.replace(choices,choices+'"p1_captacao_contracts", "p1_captacao_state", "p1_captacao_validate", "p1_captacao_persist", "p1_captacao_protect", "p1_captacao_audit", ',1)
p.write_text(s)
