from pathlib import Path
p=Path('/home/ubuntu/brasfoot_engine/scripts/career_gateway.py')
s=p.read_text()
needle='from engine.core.p1_commission_contract import audit_p1_commissions, protect_p1_commission_mutation, read_p1_commissions, read_p1_commission_state, persist_p1_commission, validate_p1_commission\n'
s=s.replace(needle, needle+'from engine.core.p1_objetivo_operacional_contract import audit_p1_objetivo_operacionals, protect_p1_objetivo_operacional_mutation, read_p1_objetivo_operacionals, read_p1_objetivo_operacional_state, persist_p1_objetivo_operacional, validate_p1_objetivo_operacional\n',1)
needle='def p1_commission_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n'
fn="""def p1_objetivo_operacional_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n    if action == 'p1_objetivo_operacional_contracts': return {'items': read_p1_objetivo_operacionals(connection), 'read_only': True}\n    if action == 'p1_objetivo_operacional_state': return {'items': read_p1_objetivo_operacional_state(connection, payload.get('objetivo_operacional_key')), 'read_only': True}\n    if action == 'p1_objetivo_operacional_validate': return validate_p1_objetivo_operacional(connection, int(payload.get('item_id')))\n    if action == 'p1_objetivo_operacional_persist': return persist_p1_objetivo_operacional(connection, str(payload.get('objetivo_operacional_key', '')), int(payload.get('objetivo_operacional_id', 0)), str(payload.get('objetivo_operacional_name', '')), dict(payload.get('objetivo_operacional_payload') or {}), payload.get('club_id'), str(payload.get('status', 'ACTIVE')), str(payload.get('actor', '')))\n    if action == 'p1_objetivo_operacional_protect': return protect_p1_objetivo_operacional_mutation(connection, int(payload.get('item_id')), str(payload.get('actor', '')), dict(payload.get('mutation') or {}))\n    if action == 'p1_objetivo_operacional_audit': return audit_p1_objetivo_operacionals(connection)\n    raise ValueError('P1_OBJETIVO_OPERACIONAL_ACTION_INVALID')\n\n"""
s=s.replace(needle,fn+needle,1)
marker='        if action in {"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit"}:\n            return {"ok": True, **p1_commission_market(service.connection, action, payload)}\n'
s=s.replace(marker,marker+'        if action in {"p1_objetivo_operacional_contracts", "p1_objetivo_operacional_state", "p1_objetivo_operacional_validate", "p1_objetivo_operacional_persist", "p1_objetivo_operacional_protect", "p1_objetivo_operacional_audit"}:\n            return {"ok": True, **p1_objetivo_operacional_market(service.connection, action, payload)}\n',1)
choices='"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit", '
s=s.replace(choices,choices+'"p1_objetivo_operacional_contracts", "p1_objetivo_operacional_state", "p1_objetivo_operacional_validate", "p1_objetivo_operacional_persist", "p1_objetivo_operacional_protect", "p1_objetivo_operacional_audit", ',1)
p.write_text(s)
