from pathlib import Path
p=Path('/home/ubuntu/brasfoot_engine/scripts/career_gateway.py')
s=p.read_text()
needle='from engine.core.p1_commission_contract import audit_p1_commissions, protect_p1_commission_mutation, read_p1_commissions, read_p1_commission_state, persist_p1_commission, validate_p1_commission\n'
s=s.replace(needle, needle+'from engine.core.p1_doctor_contract import audit_p1_doctors, protect_p1_doctor_mutation, read_p1_doctors, read_p1_doctor_state, persist_p1_doctor, validate_p1_doctor\n',1)
needle='def p1_commission_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n'
fn="""def p1_doctor_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n    if action == 'p1_doctor_contracts': return {'items': read_p1_doctors(connection), 'read_only': True}\n    if action == 'p1_doctor_state': return {'items': read_p1_doctor_state(connection, payload.get('doctor_key')), 'read_only': True}\n    if action == 'p1_doctor_validate': return validate_p1_doctor(connection, int(payload.get('item_id')))\n    if action == 'p1_doctor_persist': return persist_p1_doctor(connection, str(payload.get('doctor_key', '')), int(payload.get('doctor_id', 0)), str(payload.get('doctor_name', '')), dict(payload.get('doctor_payload') or {}), payload.get('club_id'), str(payload.get('status', 'ACTIVE')), str(payload.get('actor', '')))\n    if action == 'p1_doctor_protect': return protect_p1_doctor_mutation(connection, int(payload.get('item_id')), str(payload.get('actor', '')), dict(payload.get('mutation') or {}))\n    if action == 'p1_doctor_audit': return audit_p1_doctors(connection)\n    raise ValueError('P1_DOCTOR_ACTION_INVALID')\n\n"""
s=s.replace(needle,fn+needle,1)
marker='        if action in {"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit"}:\n            return {"ok": True, **p1_commission_market(service.connection, action, payload)}\n'
s=s.replace(marker,marker+'        if action in {"p1_doctor_contracts", "p1_doctor_state", "p1_doctor_validate", "p1_doctor_persist", "p1_doctor_protect", "p1_doctor_audit"}:\n            return {"ok": True, **p1_doctor_market(service.connection, action, payload)}\n',1)
choices='"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit", '
s=s.replace(choices,choices+'"p1_doctor_contracts", "p1_doctor_state", "p1_doctor_validate", "p1_doctor_persist", "p1_doctor_protect", "p1_doctor_audit", ',1)
p.write_text(s)
