from pathlib import Path
p=Path('/home/ubuntu/brasfoot_engine/scripts/career_gateway.py')
s=p.read_text()
needle='from engine.core.p1_commission_contract import audit_p1_commissions, protect_p1_commission_mutation, read_p1_commissions, read_p1_commission_state, persist_p1_commission, validate_p1_commission\n'
s=s.replace(needle, needle+'from engine.core.p1_promocao_contract import audit_p1_promocaos, protect_p1_promocao_mutation, read_p1_promocaos, read_p1_promocao_state, persist_p1_promocao, validate_p1_promocao\n',1)
needle='def p1_commission_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n'
fn="""def p1_promocao_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n    if action == 'p1_promocao_contracts': return {'items': read_p1_promocaos(connection), 'read_only': True}\n    if action == 'p1_promocao_state': return {'items': read_p1_promocao_state(connection, payload.get('promocao_key')), 'read_only': True}\n    if action == 'p1_promocao_validate': return validate_p1_promocao(connection, int(payload.get('item_id')))\n    if action == 'p1_promocao_persist': return persist_p1_promocao(connection, str(payload.get('promocao_key', '')), int(payload.get('promocao_id', 0)), str(payload.get('promocao_name', '')), dict(payload.get('promocao_payload') or {}), payload.get('club_id'), str(payload.get('status', 'ACTIVE')), str(payload.get('actor', '')))\n    if action == 'p1_promocao_protect': return protect_p1_promocao_mutation(connection, int(payload.get('item_id')), str(payload.get('actor', '')), dict(payload.get('mutation') or {}))\n    if action == 'p1_promocao_audit': return audit_p1_promocaos(connection)\n    raise ValueError('P1_PROMOCAO_ACTION_INVALID')\n\n"""
s=s.replace(needle,fn+needle,1)
marker='        if action in {"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit"}:\n            return {"ok": True, **p1_commission_market(service.connection, action, payload)}\n'
s=s.replace(marker,marker+'        if action in {"p1_promocao_contracts", "p1_promocao_state", "p1_promocao_validate", "p1_promocao_persist", "p1_promocao_protect", "p1_promocao_audit"}:\n            return {"ok": True, **p1_promocao_market(service.connection, action, payload)}\n',1)
choices='"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit", '
s=s.replace(choices,choices+'"p1_promocao_contracts", "p1_promocao_state", "p1_promocao_validate", "p1_promocao_persist", "p1_promocao_protect", "p1_promocao_audit", ',1)
p.write_text(s)
