from pathlib import Path
p=Path('/home/ubuntu/brasfoot_engine/scripts/career_gateway.py')
s=p.read_text()
needle='from engine.core.p1_commission_contract import audit_p1_commissions, protect_p1_commission_mutation, read_p1_commissions, read_p1_commission_state, persist_p1_commission, validate_p1_commission\n'
s=s.replace(needle, needle+'from engine.core.p1_finalization_contract import audit_p1_finalizations, protect_p1_finalization_mutation, read_p1_finalizations, read_p1_finalization_state, persist_p1_finalization, validate_p1_finalization\n',1)
needle='def p1_commission_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n'
fn="""def p1_finalization_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n    if action == 'p1_finalization_contracts': return {'items': read_p1_finalizations(connection), 'read_only': True}\n    if action == 'p1_finalization_state': return {'items': read_p1_finalization_state(connection, payload.get('finalization_key')), 'read_only': True}\n    if action == 'p1_finalization_validate': return validate_p1_finalization(connection, int(payload.get('item_id')))\n    if action == 'p1_finalization_persist': return persist_p1_finalization(connection, str(payload.get('finalization_key', '')), int(payload.get('finalization_id', 0)), str(payload.get('finalization_name', '')), dict(payload.get('finalization_payload') or {}), payload.get('club_id'), str(payload.get('status', 'ACTIVE')), str(payload.get('actor', '')))\n    if action == 'p1_finalization_protect': return protect_p1_finalization_mutation(connection, int(payload.get('item_id')), str(payload.get('actor', '')), dict(payload.get('mutation') or {}))\n    if action == 'p1_finalization_audit': return audit_p1_finalizations(connection)\n    raise ValueError('P1_FINALIZATION_ACTION_INVALID')\n\n"""
s=s.replace(needle,fn+needle,1)
marker='        if action in {"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit"}:\n            return {"ok": True, **p1_commission_market(service.connection, action, payload)}\n'
s=s.replace(marker,marker+'        if action in {"p1_finalization_contracts", "p1_finalization_state", "p1_finalization_validate", "p1_finalization_persist", "p1_finalization_protect", "p1_finalization_audit"}:\n            return {"ok": True, **p1_finalization_market(service.connection, action, payload)}\n',1)
choices='"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit", '
s=s.replace(choices,choices+'"p1_finalization_contracts", "p1_finalization_state", "p1_finalization_validate", "p1_finalization_persist", "p1_finalization_protect", "p1_finalization_audit", ',1)
p.write_text(s)
