from pathlib import Path
p=Path('/home/ubuntu/brasfoot_engine/scripts/career_gateway.py')
s=p.read_text()
needle='from engine.core.p1_commission_contract import audit_p1_commissions, protect_p1_commission_mutation, read_p1_commissions, read_p1_commission_state, persist_p1_commission, validate_p1_commission\n'
s=s.replace(needle, needle+'from engine.core.p1_intensidade_contract import audit_p1_intensidades, protect_p1_intensidade_mutation, read_p1_intensidades, read_p1_intensidade_state, persist_p1_intensidade, validate_p1_intensidade\n',1)
needle='def p1_commission_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n'
fn="""def p1_intensidade_market(connection: sqlite3.Connection, action: str, payload: dict) -> dict:\n    if action == 'p1_intensidade_contracts': return {'items': read_p1_intensidades(connection), 'read_only': True}\n    if action == 'p1_intensidade_state': return {'items': read_p1_intensidade_state(connection, payload.get('intensidade_key')), 'read_only': True}\n    if action == 'p1_intensidade_validate': return validate_p1_intensidade(connection, int(payload.get('item_id')))\n    if action == 'p1_intensidade_persist': return persist_p1_intensidade(connection, str(payload.get('intensidade_key', '')), int(payload.get('intensidade_id', 0)), str(payload.get('intensidade_name', '')), dict(payload.get('intensidade_payload') or {}), payload.get('club_id'), str(payload.get('status', 'ACTIVE')), str(payload.get('actor', '')))\n    if action == 'p1_intensidade_protect': return protect_p1_intensidade_mutation(connection, int(payload.get('item_id')), str(payload.get('actor', '')), dict(payload.get('mutation') or {}))\n    if action == 'p1_intensidade_audit': return audit_p1_intensidades(connection)\n    raise ValueError('P1_INTENSIDADE_ACTION_INVALID')\n\n"""
s=s.replace(needle,fn+needle,1)
marker='        if action in {"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit"}:\n            return {"ok": True, **p1_commission_market(service.connection, action, payload)}\n'
s=s.replace(marker,marker+'        if action in {"p1_intensidade_contracts", "p1_intensidade_state", "p1_intensidade_validate", "p1_intensidade_persist", "p1_intensidade_protect", "p1_intensidade_audit"}:\n            return {"ok": True, **p1_intensidade_market(service.connection, action, payload)}\n',1)
choices='"p1_commission_contracts", "p1_commission_state", "p1_commission_validate", "p1_commission_persist", "p1_commission_protect", "p1_commission_audit", '
s=s.replace(choices,choices+'"p1_intensidade_contracts", "p1_intensidade_state", "p1_intensidade_validate", "p1_intensidade_persist", "p1_intensidade_protect", "p1_intensidade_audit", ',1)
p.write_text(s)
