from pathlib import Path

sections = {
"1. Governança e priorização": [
"Definir a visão de produto para as próximas três temporadas simuladas.",
"Transformar o roadmap em épicos com critérios de aceite verificáveis.",
"Classificar cada iniciativa por valor, risco, dependência e esforço.",
"Criar um quadro de execução com estados descoberta, construção, validação e concluída.",
"Registrar decisões arquiteturais em documentos versionados.",
"Definir responsáveis por motor, dados, frontend, testes e operação.",
"Estabelecer uma cadência quinzenal de revisão do roadmap.",
"Criar um registro de riscos técnicos e de produto.",
"Definir métricas de sucesso para carreira, economia e partidas.",
"Separar claramente escopo essencial, avançado e experimental.",
"Criar critérios para não aceitar dados fictícios em produção.",
"Documentar quais módulos são fontes de verdade para cada domínio.",
"Definir política de compatibilidade para migrações do SQLite.",
"Criar processo de revisão antes de alterar o arquivo-mãe.",
"Registrar decisões de balanceamento com fórmula e justificativa.",
"Definir política de reprodutibilidade por seed.",
"Criar calendário de marcos para uma temporada completa.",
"Priorizar primeiro os fluxos que fecham o ciclo semanal.",
"Medir dívida técnica acumulada a cada checkpoint.",
"Publicar uma matriz de dependências entre os 500 passos.",
],
"2. Arquitetura do motor": [
"Separar contratos de domínio, persistência e apresentação em módulos explícitos.",
"Documentar o fluxo ARQUIVO-MÃE → SQL → serviço → gateway → tRPC.",
"Criar interfaces comuns para serviços transacionais.",
"Padronizar o parâmetro managed_transaction em todos os escritores.",
"Eliminar commits implícitos em context managers internos.",
"Adicionar um coordenador de unidade de trabalho para o ciclo semanal.",
"Formalizar códigos de erro de domínio em um catálogo único.",
"Criar contexto de execução com temporada, semana, seed e escopo.",
"Adicionar validação de pré-condições antes de cada etapa do tick.",
"Criar contratos de retorno serializáveis para o gateway Python.",
"Versionar o contrato de ações aceitas pelo gateway.",
"Adicionar logs estruturados sem registrar dados sensíveis.",
"Definir limites de tempo para operações mundiais em lote.",
"Criar mecanismo de cancelamento seguro para simulações longas.",
"Separar consultas de leitura de comandos mutáveis no motor.",
"Padronizar nomes de IDs, temporadas, semanas e referências naturais.",
"Adicionar verificação de esquema na inicialização dos serviços.",
"Criar relatório de dependências circulares entre módulos.",
"Documentar pontos seguros para extensão por plugins internos.",
"Construir uma suíte de contratos compartilhados entre Python e TypeScript.",
],
"3. Banco de dados e migrações": [
"Inventariar todas as tabelas do banco-base e do banco de estado.",
"Documentar as chaves naturais de cada tabela mutável.",
"Criar uma tabela de versão de esquema do estado.",
"Adicionar migrações idempotentes para todos os módulos novos.",
"Validar foreign keys após cada migração em cópia temporária.",
"Criar índices para consultas por clube e semana.",
"Criar índices para ledger por categoria e referência.",
"Criar índices para eventos por status e data.",
"Adicionar constraints contra valores negativos indevidos.",
"Adicionar constraints para níveis de estádio entre 1 e 10.",
"Adicionar constraints para público não exceder capacidade.",
"Adicionar constraints para saldo e lançamentos coerentes.",
"Documentar todas as colunas derivadas e suas fontes.",
"Criar ferramenta para comparar esquema-base e esquema de estado.",
"Criar verificação de tabelas órfãs após importação.",
"Adicionar testes de migração a partir de estados antigos.",
"Criar rotina de backup antes de migrações destrutivas.",
"Documentar estratégia de rollback de migrações não destrutivas.",
"Criar compactação controlada do SQLite após grandes temporadas.",
"Medir planos de consulta das operações mais frequentes.",
],
"4. Jogadores e dados canônicos": [
"Catalogar todas as posições originais presentes no arquivo-mãe.",
"Normalizar abreviações de posição sem perder o valor original.",
"Validar unicidade global de cada jogador.",
"Mapear histórico de vínculos entre jogador e clube.",
"Preservar status, lado, categoria e titularidade originais.",
"Adicionar validação de faixa para CR1 e CR2.",
"Adicionar evolução temporal de idade e potencial.",
"Criar histórico de atributos por temporada.",
"Criar histórico de contratos individuais.",
"Modelar cláusulas e duração de contrato.",
"Adicionar preferência de posição ao perfil do jogador.",
"Adicionar pé dominante e versatilidade quando disponíveis.",
"Criar perfil de personalidade sem inventar campos ausentes.",
"Registrar disponibilidade e suspensão em tabelas de domínio.",
"Criar consulta de topo mundial por posição.",
"Validar jogadores duplicados em importações futuras.",
"Criar relatório de jogadores sem clube.",
"Criar relatório de clubes com elenco incompleto.",
"Testar serialização de todos os perfis para o frontend.",
"Documentar o mapeamento completo do arquivo-mãe para SQL.",
],
"5. Clubes, seleções e identidades": [
"Validar os 8.399 clubes contra seus IDs oficiais.",
"Criar consulta de clubes por país e divisão.",
"Criar consulta de seleções por código e confederação.",
"Completar vínculos de escudos presentes no arquivo-mãe.",
"Registrar explicitamente ativos de clube ausentes.",
"Registrar explicitamente ativos de seleção ausentes.",
"Adicionar uniforme primário e secundário quando disponíveis.",
"Criar fallback visual consistente para identidade ausente.",
"Validar nomes duplicados com IDs distintos.",
"Criar aliases de busca sem alterar o nome canônico.",
"Adicionar dados de rivalidade somente quando documentados.",
"Modelar país, região e competição de origem.",
"Criar perfil institucional por clube.",
"Criar histórico de mudanças de nome do clube.",
"Validar relações clube-estádio sem duplicidade.",
"Criar consulta de elenco por clube controlado.",
"Adicionar filtros de clubes por força e país.",
"Testar início de carreira com clube e seleção.",
"Criar proteção contra seleção de entidade inexistente.",
"Documentar todos os fallbacks de identidade no frontend.",
],
"6. Elenco e gestão esportiva": [
"Criar visão persistida de titulares e reservas.",
"Adicionar formação titular como comando do manager.",
"Validar quantidade mínima de jogadores disponíveis.",
"Criar banco de formações salvas por competição.",
"Adicionar escalação automática baseada em posição.",
"Adicionar substituições planejadas para partidas.",
"Registrar minutos jogados por atleta.",
"Registrar gols, assistências e cartões por partida.",
"Criar cálculo de entrosamento do elenco.",
"Criar impacto de moral na escalação.",
"Adicionar bloqueio de atleta lesionado.",
"Adicionar bloqueio de atleta suspenso.",
"Criar relatório de profundidade por posição.",
"Sinalizar posições sem cobertura adequada.",
"Adicionar gestão de capitão e cobradores.",
"Criar histórico de decisões táticas.",
"Exibir condição física antes da partida.",
"Exibir risco de fadiga por calendário.",
"Adicionar confirmação de escalação antes do jogo.",
"Testar todas as escalações contra regras do campeonato.",
],
"7. Comissão técnica e departamentos": [
"Completar catálogo de funções profissionais do motor.",
"Validar níveis e atributos de cada profissional.",
"Adicionar contratos e duração para staff contratado.",
"Criar custo de rescisão de profissionais.",
"Adicionar substituição de profissional ativo.",
"Registrar efeito de cada função no domínio correspondente.",
"Criar limites de vagas por departamento.",
"Adicionar bônus de comissão por nível.",
"Adicionar médicos por especialidade quando existirem.",
"Adicionar auxiliares por área tática.",
"Criar histórico de contratações da comissão.",
"Criar consulta de folha individual de staff.",
"Adicionar filtro de mercado por função e nível.",
"Adicionar ordenação por custo-benefício.",
"Criar confirmação antes de contratar profissional.",
"Exibir ausência real de staff no CT.",
"Adicionar alertas de contrato prestes a expirar.",
"Criar impacto de staff na recuperação de atletas.",
"Testar contratação simultânea com concorrência SQLite.",
"Documentar o catálogo sem criar profissionais fictícios em produção.",
],
"8. Centro de treinamento e evolução": [
"Inventariar todos os departamentos de CT disponíveis.",
"Definir níveis máximos e custos por departamento.",
"Adicionar histórico de evolução do CT.",
"Criar manutenção semanal específica por departamento.",
"Calcular impacto de CT no overall institucional.",
"Adicionar instalações de base quando existirem no SQL.",
"Criar programa de desenvolvimento individual.",
"Adicionar carga de treino por grupo.",
"Adicionar recuperação e descanso planejados.",
"Criar plano semanal de treinamento persistido.",
"Impedir treino incompatível com lesão ativa.",
"Calcular risco de lesão por carga.",
"Adicionar bônus de staff ao treinamento.",
"Criar relatório de evolução por atleta.",
"Adicionar comparação entre potencial e desempenho.",
"Criar tela de orçamento de melhorias.",
"Adicionar previsão de retorno de cada departamento.",
"Emitir alerta para falta de manutenção.",
"Testar rollback de compra de departamento.",
"Validar sincronização de CT com folha semanal.",
],
"9. Treinamento, forma e moral": [
"Criar estados de forma física e técnica.",
"Definir atualização de forma após cada partida.",
"Adicionar moral individual persistida.",
"Adicionar moral coletiva do elenco.",
"Modelar efeito de vitória e derrota na moral.",
"Modelar efeito de sequência de jogos.",
"Criar treinamento técnico por posição.",
"Criar treinamento tático por formação.",
"Criar treinamento físico com risco calculado.",
"Adicionar sessões de bola parada.",
"Adicionar preparação específica para adversário.",
"Registrar aderência do elenco ao plano.",
"Criar relatório de carga semanal.",
"Adicionar limite de carga por idade.",
"Adicionar descanso após partidas congestionadas.",
"Criar impacto do calendário internacional.",
"Exibir recomendações baseadas em fatos persistidos.",
"Testar determinismo da evolução por seed.",
"Testar rollback de forma após falha do tick.",
"Documentar fórmulas de forma e moral.",
],
"10. Lesões, saúde e suspensões": [
"Inventariar tabelas de lesões já existentes.",
"Criar estados de lesão com início e previsão de retorno.",
"Registrar diagnóstico e gravidade.",
"Adicionar recuperação diária ou semanal.",
"Aplicar influência médica na recuperação.",
"Impedir escalação de lesionados.",
"Registrar recaída com regra determinística.",
"Adicionar suspensão por cartões.",
"Adicionar suspensão por expulsão.",
"Criar histórico médico do atleta.",
"Emitir alerta de lesão nova.",
"Emitir alerta de retorno ao elenco.",
"Criar tela de departamento médico.",
"Adicionar prognóstico sem prometer precisão clínica real.",
"Testar lesões em partidas de pré-temporada.",
"Testar lesão no meio do ciclo semanal.",
"Testar rollback de lesão após falha posterior.",
"Validar que saúde não inventa jogadores.",
"Adicionar filtros por gravidade e prazo.",
"Documentar limites do modelo de saúde do jogo.",
],
"11. Motor de partidas": [
"Documentar todas as entradas do MatchEngine.",
"Separar geração de resultado e aplicação do resultado.",
"Fixar seed em cada partida persistida.",
"Calibrar vantagem de mando com dados internos.",
"Calibrar influência de força do elenco.",
"Adicionar influência de forma e moral.",
"Adicionar influência de tática escolhida.",
"Adicionar eventos de gol persistidos.",
"Adicionar cartões e substituições persistidos.",
"Adicionar estatísticas de finalizações.",
"Adicionar posse de bola quando suportada.",
"Adicionar expected goals somente com fórmula documentada.",
"Criar validação de placar não negativo.",
"Criar limite de eventos por partida.",
"Testar confrontos entre clubes reais.",
"Testar partida sem competição vinculada.",
"Testar partida adiada e remarcada.",
"Testar execução duplicada da mesma partida.",
"Testar rollback após resultado parcialmente aplicado.",
"Criar relatório de distribuição de placares por temporada.",
],
"12. Competições e classificação": [
"Inventariar formatos de competição presentes no motor.",
"Criar configuração de pontos por resultado.",
"Adicionar critérios de desempate documentados.",
"Validar criação de grupos e rodadas.",
"Adicionar mata-mata com ida e volta.",
"Adicionar disputa de pênaltis quando aplicável.",
"Criar classificação derivada de partidas PLAYED.",
"Impedir alteração manual de tabela pelo frontend.",
"Adicionar status de competição por fase.",
"Criar regras para partidas suspensas.",
"Adicionar calendário de finais.",
"Adicionar promoção e rebaixamento configuráveis.",
"Criar histórico de campeões.",
"Configurar premiações por posição.",
"Validar premiação somente ao concluir competição.",
"Impedir pagamento duplicado de premiação.",
"Adicionar alertas de classificação.",
"Criar consulta de competição no gateway.",
"Testar temporadas com múltiplas competições.",
"Documentar limitações das competições ainda não configuradas.",
],
"13. Calendário e temporadas": [
"Formalizar o relógio lógico de temporada e semana.",
"Criar calendário de pré-temporada.",
"Criar calendário de temporada regular.",
"Adicionar janelas de descanso.",
"Adicionar datas de competições simultâneas.",
"Criar mecanismo de adiamento por conflito.",
"Validar semana sem partidas.",
"Validar semana com várias partidas.",
"Criar avanço diário opcional para serviços internos.",
"Manter avanço semanal como comando principal do manager.",
"Adicionar bloqueio de avanço para estado inválido.",
"Criar histórico de cada avanço.",
"Adicionar previsão do próximo compromisso.",
"Criar consulta de agenda por clube.",
"Adicionar pausas entre temporadas.",
"Criar transição de elenco entre temporadas.",
"Fechar contratos ao término da temporada.",
"Gerar relatório de calendário congestionado.",
"Testar avanço repetido com a mesma chave.",
"Testar restauração de relógio após rollback.",
],
"14. IA dos clubes": [
"Definir objetivos esportivos por clube.",
"Definir orçamento disponível para IA.",
"Criar avaliação automática de elenco.",
"Criar escalação automática da IA.",
"Adicionar escolha tática da IA.",
"Adicionar priorização de competições.",
"Criar contratação orientada por necessidade.",
"Criar venda orientada por orçamento.",
"Adicionar renovação de contratos da IA.",
"Adicionar evolução de departamentos pela IA.",
"Criar comportamento distinto por nível institucional.",
"Adicionar efeito da reputação nas decisões.",
"Criar planejamento de janela de transferências.",
"Registrar decisões da IA em histórico.",
"Criar explicação legível para decisões relevantes.",
"Impedir que a IA escreva fora das transações do motor.",
"Testar IA com seed determinística.",
"Testar IA em banco mundial isolado.",
"Medir tempo de simulação de milhares de clubes.",
"Criar limites para evitar decisões economicamente impossíveis.",
],
"15. Transferências e mercado": [
"Inventariar contratos e vínculos atuais de jogadores.",
"Criar janela de transferências configurável.",
"Adicionar lista de jogadores transferíveis.",
"Adicionar propostas entre clubes do mundo.",
"Criar negociação de valor e salário.",
"Adicionar empréstimos com duração.",
"Adicionar opção de compra quando suportada.",
"Registrar taxa de transferência no ledger.",
"Registrar comissão e custos acessórios.",
"Validar saldo antes de concluir negócio.",
"Validar vagas de elenco antes de contratar.",
"Impedir transferência de jogador suspenso em condição proibida.",
"Criar histórico de cada negociação.",
"Adicionar aprovação do manager para propostas recebidas.",
"Emitir alerta de transferência concluída.",
"Criar evento de transferência cancelada.",
"Testar concorrência entre propostas.",
"Testar rollback após débito de transferência.",
"Separar dados fictícios de cenários de teste.",
"Documentar a política de não usar dados reais inventados.",
],
"16. Scouting e base": [
"Inventariar missões de scouting existentes.",
"Criar regiões de observação configuráveis.",
"Adicionar duração e custo de cada missão.",
"Registrar relatório de observação persistido.",
"Separar descoberta de contratação.",
"Adicionar filtros por posição e faixa etária.",
"Adicionar filtro por potencial quando disponível.",
"Criar prioridade de missão por necessidade do elenco.",
"Adicionar staff de scouting ao cálculo.",
"Emitir alerta de relatório concluído.",
"Criar comparação entre relatório e atributos reais.",
"Impedir contratação sem confirmação do manager.",
"Adicionar base de formação quando houver dados canônicos.",
"Criar progressão de atletas da base.",
"Registrar promoção ao elenco profissional.",
"Adicionar custo de manutenção da base.",
"Testar determinismo de descobertas por seed.",
"Testar expiração de missão de scouting.",
"Criar tela de relatórios disponíveis.",
"Documentar campos que não existem no arquivo-mãe.",
],
"17. Economia mundial": [
"Documentar todas as categorias do FinanceLedger.",
"Criar moeda e unidade monetária únicas no motor.",
"Validar lançamentos com referência natural.",
"Adicionar fechamento semanal do ledger.",
"Criar relatório de receitas por clube.",
"Criar relatório de despesas por clube.",
"Adicionar projeção de caixa para 39 semanas.",
"Preservar a reserva de 39 semanas da fórmula original.",
"Adicionar receita de bilheteria por partida.",
"Adicionar manutenção de estádio por semana.",
"Adicionar folha individual de jogadores.",
"Adicionar folha de comissão e departamentos.",
"Criar alerta de saldo baixo.",
"Criar regra de déficit controlado.",
"Definir comportamento de insolvência.",
"Modelar recuperação financeira sem valores arbitrários.",
"Adicionar relatórios de economia mundial.",
"Testar idempotência de cada categoria de lançamento.",
"Testar rollback de caixa após falha tardia.",
"Criar ferramenta de auditoria por temporada.",
],
"18. Finanças do clube": [
"Criar painel de caixa atual e projetado.",
"Separar saldo disponível de receitas futuras.",
"Exibir folha semanal individualizada.",
"Exibir manutenção semanal consolidada.",
"Exibir receitas de patrocínio ativas.",
"Exibir bilheteria das últimas partidas.",
"Exibir premiações recebidas por competição.",
"Criar filtros por semana e categoria.",
"Criar detalhe de cada lançamento do ledger.",
"Adicionar exportação financeira em CSV.",
"Adicionar bloqueio visual para saldo insuficiente.",
"Criar confirmação para despesas irreversíveis.",
"Adicionar previsão de caixa pós-próxima partida.",
"Exibir impacto de uma contratação antes de confirmar.",
"Criar alerta para contratos comerciais expirando.",
"Adicionar comparação entre orçamento e realizado.",
"Criar histórico financeiro por temporada.",
"Testar arredondamentos monetários.",
"Testar transações concorrentes sobre o mesmo clube.",
"Documentar que o frontend nunca calcula o saldo.",
],
"19. Estádio e infraestrutura": [
"Completar regras de custo por componente do estádio.",
"Validar níveis de arquibancada de 1 a 10.",
"Validar níveis de campo de 1 a 10.",
"Validar níveis de estrutura de 1 a 10.",
"Validar níveis de equipes de 1 a 10.",
"Adicionar histórico de cada upgrade.",
"Adicionar previsão de capacidade após upgrade.",
"Adicionar previsão de qualidade de matchday.",
"Calcular manutenção de cada componente.",
"Emitir alerta de evolução concluída.",
"Criar alerta de manutenção onerosa.",
"Adicionar estado de estádio indisponível.",
"Adicionar estádio neutro para partidas especiais.",
"Criar regras de reforma durante a temporada.",
"Adicionar limite de capacidade por competição.",
"Exibir estádio real no dashboard do clube.",
"Criar histórico visual de evolução.",
"Testar bootstrap mundial repetido.",
"Testar upgrade com caixa insuficiente.",
"Testar rollback de upgrade em falha do ledger.",
],
"20. Torcida, reputação e público": [
"Separar torcida de reputação esportiva e comercial.",
"Definir tamanho inicial da torcida por dado canônico.",
"Atualizar satisfação após cada partida jogada.",
"Atualizar engajamento após cada partida jogada.",
"Atualizar interesse por competição.",
"Modelar efeito gradual de vitórias.",
"Modelar efeito gradual de derrotas.",
"Modelar efeito de sequência invicta.",
"Modelar efeito de estádio e conforto.",
"Calcular demanda com seed determinística.",
"Impedir público negativo.",
"Impedir público acima da capacidade.",
"Aplicar preço de ingresso do motor.",
"Registrar público esperado e realizado.",
"Criar histórico de público por partida.",
"Emitir alerta de recorde de público.",
"Emitir alerta de queda relevante de presença.",
"Criar painel de satisfação da torcida.",
"Testar repetição da mesma partida sem dupla atualização.",
"Documentar todas as fórmulas sociais.",
],
"21. Patrocínios e mídia": [
"Completar catálogo de marcas por estrela.",
"Definir requisitos institucionais por proposta.",
"Rotacionar ofertas expiradas sem aceite automático.",
"Preservar propostas aceitas no histórico.",
"Adicionar contratos de seis semanas configuráveis.",
"Calcular sinal inicial no ledger.",
"Calcular receita semanal no ledger.",
"Adicionar missões por vitórias.",
"Adicionar missões por gols.",
"Adicionar missões por público.",
"Adicionar missão de classificação.",
"Registrar progresso somente por fatos SQL.",
"Impedir progresso duplicado por partida.",
"Emitir alerta de contrato aceito.",
"Emitir alerta de missão concluída.",
"Emitir alerta de proposta expirada.",
"Adicionar slots de patrocinadores secundários.",
"Criar mídia e direitos de transmissão configuráveis.",
"Testar rollback de aceitação comercial.",
"Documentar critérios de elegibilidade e estrelas.",
],
"22. Eventos, alertas e notícias": [
"Completar índices da tabela club_events.",
"Padronizar referências idempotentes de eventos.",
"Adicionar origem técnica de cada alerta.",
"Adicionar impacto financeiro estruturado.",
"Adicionar eventos de contratação de staff.",
"Adicionar eventos de departamento evoluído.",
"Adicionar eventos de transferência.",
"Adicionar eventos de lesão.",
"Adicionar eventos de suspensão.",
"Adicionar eventos de partida concluída.",
"Adicionar eventos de premiação paga.",
"Adicionar eventos de caixa baixo.",
"Adicionar eventos de reputação alterada.",
"Adicionar severidade calculada por impacto.",
"Adicionar leitura individual persistida.",
"Adicionar marcação de todos como lidos.",
"Criar paginação do feed por data.",
"Criar filtros por tipo e severidade.",
"Adicionar feed de notícias ao dashboard.",
"Testar deduplicação e rollback de eventos.",
],
"23. Frontend e tRPC": [
"Completar tipos TypeScript para todos os retornos do gateway.",
"Separar routers tRPC por domínio de negócio.",
"Adicionar validação Zod a todas as mutations.",
"Padronizar conversão de erros de domínio.",
"Adicionar estados de carregamento por componente.",
"Adicionar estados de vazio honestos por consulta.",
"Adicionar estados de erro recuperáveis.",
"Invalidar queries após cada mutation relevante.",
"Evitar qualquer fetch direto de regras esportivas.",
"Adicionar consulta de eventos persistidos.",
"Adicionar tela detalhada de finanças.",
"Adicionar tela detalhada de torcida.",
"Adicionar tela detalhada de competição.",
"Adicionar tela detalhada de calendário.",
"Adicionar tela de histórico do estádio.",
"Adicionar navegação para detalhes de alertas.",
"Adicionar acessibilidade aos controles do manager.",
"Adicionar atalhos de teclado documentados.",
"Adicionar tratamento de sessão expirada.",
"Validar todos os fluxos em viewport móvel.",
],
"24. UX e design editorial": [
"Refinar hierarquia tipográfica do Editorial de Arquibancada.",
"Padronizar espaçamento entre seções.",
"Criar tokens para cores de status.",
"Garantir contraste em todos os painéis.",
"Adicionar foco visível a todos os botões.",
"Revisar ordem de leitura para leitores de tela.",
"Adicionar textos alternativos para escudos e estádios.",
"Reduzir movimentos para prefers-reduced-motion.",
"Criar feedback visual para mutations em andamento.",
"Criar confirmação para ações financeiras.",
"Adicionar desfazer apenas onde houver comando seguro.",
"Criar skeletons específicos para tabelas.",
"Criar empty states com próxima ação clara.",
"Padronizar mensagens de erro em português.",
"Adicionar filtro persistente por seção.",
"Melhorar visualização em 375px.",
"Validar tablet em 768px.",
"Validar desktop amplo em 1440px.",
"Documentar decisões de composição visual.",
"Criar revisão visual a cada novo domínio.",
],
"25. Testes, entrega e operação": [
"Executar a suíte Python completa em cada checkpoint.",
"Executar a suíte Vitest completa em cada checkpoint.",
"Executar TypeScript check antes de cada entrega.",
"Executar build de produção antes de publicar.",
"Criar testes de contrato Python-TypeScript.",
"Criar testes de concorrência SQLite.",
"Criar testes de rollback para cada etapa do tick.",
"Criar testes de idempotência para cada escritor.",
"Criar testes de determinismo por seed.",
"Criar cenário de temporada completa em banco temporário.",
"Criar cenário de múltiplas temporadas.",
"Criar teste de não alteração do banco-base.",
"Criar teste de integridade e foreign keys.",
"Criar teste de recuperação após processo interrompido.",
"Criar relatório de cobertura por domínio.",
"Criar benchmark do bootstrap dos 8.399 clubes.",
"Criar benchmark de avanço mundial.",
"Criar README de instalação e operação segura.",
"Gerar manifesto e hash de cada pacote entregue.",
"Salvar checkpoint antes de cada publicação.",
],
}

assert len(sections) == 25
assert all(len(items) == 20 for items in sections.values())

priorities = {
    "1. Governança e priorização": "P0",
    "2. Arquitetura do motor": "P0",
    "3. Banco de dados e migrações": "P0",
    "4. Jogadores e dados canônicos": "P0",
    "5. Clubes, seleções e identidades": "P0",
    "6. Elenco e gestão esportiva": "P1",
    "7. Comissão técnica e departamentos": "P1",
    "8. Centro de treinamento e evolução": "P1",
    "9. Treinamento, forma e moral": "P1",
    "10. Lesões, saúde e suspensões": "P1",
    "11. Motor de partidas": "P0",
    "12. Competições e classificação": "P0",
    "13. Calendário e temporadas": "P0",
    "14. IA dos clubes": "P2",
    "15. Transferências e mercado": "P1",
    "16. Scouting e base": "P2",
    "17. Economia mundial": "P0",
    "18. Finanças do clube": "P1",
    "19. Estádio e infraestrutura": "P1",
    "20. Torcida, reputação e público": "P1",
    "21. Patrocínios e mídia": "P1",
    "22. Eventos, alertas e notícias": "P1",
    "23. Frontend e tRPC": "P0",
    "24. UX e design editorial": "P1",
    "25. Testes, entrega e operação": "P0",
}
assert set(priorities) == set(sections)
dependencies = {
    1: [], 2: [1], 3: [1, 2], 4: [3], 5: [3, 4],
    6: [4, 5], 7: [3, 5], 8: [3, 7], 9: [6, 8], 10: [6, 8, 9],
    11: [2, 3, 4, 6, 9], 12: [3, 5, 11], 13: [2, 3, 12], 14: [6, 11, 12, 13],
    15: [3, 4, 5, 6, 13], 16: [4, 6, 7, 8], 17: [2, 3, 5, 13], 18: [3, 17],
    19: [3, 17], 20: [5, 11, 12, 19], 21: [17, 18, 19, 20], 22: [11, 17, 19, 20, 21],
    23: [2, 3, 5, 11, 12, 13, 17], 24: [23], 25: [2, 3, 11, 12, 13, 17, 23],
}
assert set(dependencies) == set(range(1, 26))

out = ["# FutManager/Brasfoot — 500 próximos passos", "", "> Roadmap expandido em 25 frentes. A numeração é contínua para facilitar priorização, delegação e acompanhamento.", "", "## Critérios de priorização", "", "| Nível | Critério | Ordem recomendada |", "|---|---|---|", "| P0 | Fundação, integridade, fonte de verdade, ciclo jogável e bloqueios de entrega. | Executar primeiro. |", "| P1 | Funcionalidades que aprofundam a carreira, a gestão e a experiência principal depois da fundação. | Executar após os pré-requisitos P0. |", "| P2 | Sistemas avançados, expansão de simulação e melhorias de longo prazo. | Executar quando P0/P1 estiverem estáveis. |", "", "A prioridade da frente orienta os 20 itens nela contidos; dentro de cada frente, a ordem numérica é a ordem sugerida de execução e dependência.", "", "## Regra obrigatória de execução", "", "> Nenhum item P1 ou P2 pode ser iniciado, mesclado ou marcado como concluído enquanto todos os itens P0 não estiverem consolidados com implementação, testes, integridade SQLite, documentação e evidência no gate versionado.", "", "O roadmap registra planejamento; ele não é fonte de verdade do jogo. O estado esportivo, financeiro, social e de carreira continua vindo exclusivamente de SQL/GameState. O frontend apenas consulta e solicita comandos por tRPC/Gateway; não calcula, inventa ou grava estado de jogo.", "", "Situação inicial deste documento: **P1 e P2 bloqueados** até o gate P0 ser aprovado.", "", "## Matriz verificável de dependências", "", "| Frente | Prioridade | Depende de |", "|---:|:---:|:---|", *[f"| {front} | {priorities[list(sections)[front - 1]]} | {', '.join(str(dep) for dep in dependencies[front]) if dependencies[front] else 'fundação'} |" for front in range(1, 26)], "", "A matriz é de fronts; cada ação numerada herda a dependência de sua frente. Um front só pode ser aberto depois de seus dependentes e do gate P0, quando sua prioridade for P1 ou P2.", ""]
number = 1
for title, items in sections.items():
    out.extend([f"## [{priorities[title]}] {title}", ""])
    for item in items:
        out.append(f"{number}. {item}")
        number += 1
    out.append("")

assert number == 501
Path("/home/ubuntu/futmanager_frontend/roadmap_500_proximos_passos.md").write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"generated={number - 1}")
