from pathlib import Path
import json

DOMAINS = [
('Persistência e migrações', ['inventário de tabelas pós-700','migração incremental v4','chaves naturais','índices de leitura','índices de auditoria','constraints de domínio','versionamento de schema','rollback seguro','checksum do GameState','detector de drift','catálogo de enums','normalização de datas UTC','retenção de auditoria','snapshots transacionais','restauração seletiva','validadores de foreign keys','testes de cópia física','relatório de migração','compatibilidade v3','documentação de persistência']),
('Gateway e contratos', ['contrato de leitura consolidado','mapa de writers autorizados','validação de payload','catálogo de erros','idempotência por comando','escopo de carreira','permissões por manager','paginação estável','filtros tipados','auditoria de mutação','rollback de comando','limites de lote','timeout controlado','telemetria de RPC','contratos de versão','testes de integração','proteção contra escrita frontend','serialização de datas','compatibilidade de clientes','documentação do gateway']),
('Calendário mundial', ['feriados nacionais','datas FIFA','conflitos de seleção','janelas internacionais','fuso do estádio','mudança de horário','reagendamento por clima','reagendamento por segurança','conflito de televisão','prioridade de competição','descanso mínimo','viagem intercontinental','calendário juvenil','calendário feminino','calendário de base','datas de inscrição','bloqueio de sobreposição','prévia de temporada','auditoria de alterações','documentação do calendário']),
('Competições avançadas', ['fase de grupos','sorteio com potes','sorteio protegido','mata-mata com ida e volta','prorrogação','disputa de pênaltis','regra de gol fora configurável','critério de confronto direto','premiação por fase','vagas continentais','rebaixamento adicional','repescagem','licença competitiva','fair play de competição','árbitros suspensos','delegado de partida','protesto oficial','revisão de resultado','homologação de competição','documentação competitiva']),
('Motor de partidas', ['modelo de posse','finalizações persistidas','xG determinístico','duelos individuais','bolas paradas','escanteios','faltas táticas','substituições condicionais','instruções de intervalo','plano de jogo','efeito de torcida','efeito climático','fadiga por minuto','lesão durante partida','cartão acumulado','VAR configurável','árbitro por perfil','eventos anulados','reprocessamento auditado','documentação do motor']),
('Elenco e contratos', ['status de inscrição','limite de estrangeiros','número de camisa','hierarquia do elenco','liderança do vestiário','promessa de minutos','cláusula de saída','bônus por presença','bônus por gol','bônus de título','renovação automática','opção unilateral','rescisão por justa causa','compensação contratual','contrato de base','contrato profissional','registro federativo','bloqueio salarial','auditoria contratual','documentação contratual']),
('Treino e desenvolvimento', ['microciclo semanal','periodização mensal','carga por posição','carga individual adaptativa','objetivo por atributo','treino técnico','treino tático','treino físico','treino mental','integração com comissão','risco acumulado','recuperação ativa','monitoramento de evolução','potencial atualizado','declínio por idade','tutoria de jovens','avaliação pós-treino','aprovação médica','cancelamento transacional','documentação de desenvolvimento']),
('Saúde e performance', ['triagem pré-jogo','risco de lesão','protocolo de concussão','retorno progressivo','carga médica','histórico de sintomas','reincidência ponderada','suspensão médica','aptidão por minuto','monitoramento de sono','fadiga acumulada','fisioterapia por fase','especialidade médica','fila de atendimento','custo clínico','alerta de risco','prévia de escalação','auditoria de laudo','integração com treino','documentação de saúde']),
('Mercado e scouting', ['shortlist por posição','shortlist por região','shortlist por orçamento','avaliação de valor','avaliação de potencial','proposta condicionada','contraproposta limitada','comissão de agente','luvas de contratação','janela internacional','empréstimo com opção','cláusula de recompra','venda com percentual futuro','bloqueio por registro','scouting por evidência','relatório de adversário','qualidade de amostra','expiração de relatório','auditoria de negociação','documentação de mercado']),
('Economia e finanças', ['orçamento por departamento','forecast semanal','forecast mensal','fluxo de caixa','reserva de emergência','limite de folha','custo de oportunidade','receita de bilheteria','receita de mídia','receita comercial','premiação competitiva','impostos configuráveis','despesas extraordinárias','auditoria de saldo','reconciliação por fonte','alerta de caixa','prévia financeira','aprovação de gasto','estorno financeiro','documentação econômica']),
('Estádio, torcida e mídia', ['setores de estádio','preço dinâmico','demanda por setor','cortesias auditáveis','estorno de ingresso','segurança de lotação','conforto por setor','receita de hospitalidade','lojas do estádio','bilheteria visitante','torcida organizada','satisfação de torcedores','reputação comercial','direitos de transmissão','audiência regional','audiência internacional','catálogo de notícias','feed por evento oficial','alertas de mídia','documentação de estádio e mídia']),
('Governança e carreira', ['conselho administrativo','mandatos de conselheiros','votação persistida','quórum configurável','conflito de interesse','ata de reunião','aprovação extraordinária','limite financeiro do conselho','pendências do conselho','histórico de composição','objetivos do manager','avaliação do manager','ofertas de emprego','negociação de contrato','seleção nacional','reputação do manager','snapshot de carreira','retomada de carreira','exportação de histórico','documentação de governança']),
]

PRIORITIES = ['P0'] * 3 + ['P1'] * 15 + ['P2'] * 2

def main():
    rows=[]
    step=701
    for domain, tasks in DOMAINS:
        for i, task in enumerate(tasks):
            priority=PRIORITIES[i]
            previous = f'{step-1}' if step > 701 else '501–700'
            criterion = f'{task.capitalize()} é persistido no GameState, exposto por leitura autorizada e coberto por teste focado.'
            rows.append((step, priority, domain, f'Implementar {task}.', previous, criterion))
            step += 1
    assert len(rows) == 240
    out=['# Roadmap FutManager — passos 701–940\n','Esta lista contém 240 implementações posteriores ao marco 700. A ordem numérica é obrigatória; P1 e P2 dependem da consolidação dos P0. SQL/GameState permanece como única fonte da verdade, e cada item exige writer autorizado quando houver mutação, leitura pelo gateway e teste focado.\n','| Passo | Prioridade | Domínio | Implementação | Dependência | Critério verificável |\n|---:|:---:|---|---|---|---|']
    out += [f'| {n} | {p} | {d} | {t} | {dep} | {c} |' for n,p,d,t,dep,c in rows]
    out += ['\n## Distribuição\n','| Prioridade | Quantidade | Regra |\n|---|---:|---|','| P0 | 36 | Infraestrutura, contratos e segurança de estado devem ser consolidados primeiro. |','| P1 | 180 | Domínios operacionais executados somente após P0 aberto. |','| P2 | 24 | Melhorias estratégicas executadas após P0 e P1 do domínio. |','| **Total** | **240** | Passos 701–940. |','\n## Regras de execução\n','Cada passo deve preservar a separação entre ReadRepository e CommandService, bloquear escrita direta no frontend, usar datas UTC no armazenamento e registrar auditoria para decisões mutáveis. Prévia não persiste alterações. Testes históricos não precisam ser refeitos; apenas testes focados novos devem ser adicionados.\n']
    path=Path('/home/ubuntu/futmanager_frontend/docs/novas_240_implementacoes_701_940.md')
    path.write_text('\n'.join(out), encoding='utf-8')
    Path('/home/ubuntu/futmanager_frontend/docs/validacao_novas_240_implementacoes.json').write_text(json.dumps({'status':'VALID','total':len(rows),'first':rows[0][0],'last':rows[-1][0],'priorities':{p:sum(r[1]==p for r in rows) for p in sorted(set(r[1] for r in rows))},'domains':len(DOMAINS)},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

if __name__ == '__main__': main()
